name: datanest
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - pandas<=2.1.4    
  - matplotlib
  - plotly
  - scikit-learn
  - xgboost       
  - lightgbm     
  - streamlit<=1.31.0 
  - requests
  - python-dotenv
  - pyarrow<=14.0.1
  - numpy
  - pip
  - seaborn
